# Data Processing Hyperparameters
processing:
  normalization: 'zscore'
  log: false
  gmm:
    max_components: 1
    epsilon: 1.0e-06

model:
  residual_modeling: false
  semi_supervised: false
  generator:
    noise_dim: 64
    hidden_dim: 256
    layers: 2
    dropout: 0.5

  discriminator:
    hidden_dim: 256
    layers: 2
    pack: 1

sample:
  m: 5
  mi_approx: None
  pmm: false
  donors: 5

train:
  epochs: 10000
  batch_size: 500
  Adam:
    lr_g: 0.0002
    lr_d: 0.0002
    betas_g: [0.5, 0.9]
    betas_d: [0.5, 0.9]
    weight_decay: 1.0e-06
  SGD:
    lr_g: 1.0e-2
    momentum_g: 0.9
    lr_d: 1.0e-2
    momentum_d: 0.9
    weight_decay: 1.0e-4
  loss:
    lambda_gp: 10
    loss_mse: 0
    loss_ce: 0
    loss_mml: 0
    loss_info: 1
    tau: 0.2
    hard_gumbel: false
    discriminator_steps: 1